---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
      - always

- name: check-set-parameters
  include: logstash-parameters.yml
  tags:
      - always

- name: include java.yml
  include: java.yml
  when: ls_java_install
  tags:
      - java

#Add required configuration to ElasticSearch
# - name: include logstash-ES-configuration.yml
#   include: logstash-ES-configuration.yml
#   tags:
#       - config

- name: include logstash.yml
  include: logstash.yml
  tags:
      - install

- name: include logstash-config.yml
  include: logstash-config.yml
  tags:
      - config

- name: include logstash-plugins.yml
  include: logstash-plugins.yml
  when: ls_plugins is defined or ls_plugins_reinstall
  tags:
      - plugins

  #We always execute xpack as we may need to remove features
- name: include xpack/logstash-xpack.yml
  include: xpack/logstash-xpack.yml
  tags:
      - xpack

- name: flush handlers
  meta: flush_handlers

- name: Make sure logstash is started
  service: name=logstash state=restarted enabled=yes
  when: ls_start_service
  become: yes
