---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
      - always

- name: check-set-parameters
  include: logstash-parameters.yml
  tags:
      - always

- name: include java.yml
  include: java.yml
  when: ls_java_install

- name: include memcached.yml
  include: memcached.yml
  when: ls_memcached_install

- name: include logstash.yml
  include: logstash.yml

- name: include logstash-config.yml
  include: logstash-config.yml

- name: Make sure logstash is stopped
  service: name=logstash state=stopped enabled=yes
  when: ls_start_service
  become: yes

- name: include logstash-plugins.yml
  include: logstash-plugins.yml
  when: ls_plugins is defined or ls_plugins_reinstall

#   #We always execute xpack as we may need to remove features
# - name: include xpack/logstash-xpack.yml
#   include: xpack/logstash-xpack.yml
#   tags:
#       - xpack
- name: Generate SSL/TLS environment
  include: xpack/logstash-xpack-ssl.yml

- name: flush handlers
  meta: flush_handlers

- name: Make sure logstash is started
  service: name=logstash state=restarted enabled=yes
  when: ls_start_service
  become: yes
