
- name: reload systemd configuration
  become: yes
  command: systemctl daemon-reload

# Restart service and ensure it is enabled
- name: restart logstash
  become: yes
  service: name=logstash state=restarted enabled=yes
  when:
    - ls_restart_on_change
    - ls_start_service
  register: ls_restarted

  - name: restart memcached
  become: yes
  service: name=memcached state=restarted enabled=yes