
- name: reload systemd configuration
  become: true
  command: systemctl daemon-reload

# Restart service and ensure it is enabled

- name: restart logstash
  become: true
  service: name=logstash state=restarted enabled=yes
  when:
    - ls_restart_on_change
    - ls_start_service
  register: ls_restarted
