---

- name: set fact ls_version_changed
  set_fact: ls_version_changed={{ ((logstash_install_from_package is defined and (debian_logstash_install_from_repo.changed or redhat_logstash_install_from_repo.changed)) or (logstash_install_from_package is defined and logstash_install_from_package.changed)) }}

- name: include logstash-xpack-install.yml
  include: logstash-xpack-install.yml

#Add any feature specific configuration here
- name: Set Plugin Directory Permissions
  become: true
  file: state=directory path={{ ls_home }}/plugins owner={{ ls_user }} group={{ ls_group }} recurse=yes

#Make sure logstash.keystore has correct Permissions
# - name: Set logstash.keystore Permissions
#   become: true
#   file: state=file path=/var/lib/logstash/logstash.keystore owner={{ ls_user }} group={{ ls_group }}
#   when: ls_enable_xpack and (ls_version | version_compare('6.0.0', '>'))
